language: python
python:
  - "3.6.3"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py

notifications:
  email: false    # default notification method
  slack:
    rooms:
      - eligere-123:Sfcq6L0AM5P9D1xT8NRjdu5W#ci-notification
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"