"""Added Faculty Table

Revision ID: 48fd099f659d
Revises: 1ccad8affaf2
Create Date: 2020-01-25 19:14:07.291403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fd099f659d'
down_revision = '1ccad8affaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('elective_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_elective_id'), 'faculty', ['elective_id'], unique=False)
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_elective_id'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
