"""empty message

Revision ID: 93ae00405c88
Revises: eed6fc910327
Create Date: 2020-02-11 20:38:48.442646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ae00405c88'
down_revision = 'eed6fc910327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'roll_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('roll_no', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
