"""Initial Electives Table

Revision ID: b4c5347b0855
Revises: 116d02170244
Create Date: 2020-01-16 11:47:18.692328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c5347b0855'
down_revision = '116d02170244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_elective_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electiveID', sa.String(length=64), nullable=True),
    sa.Column('electiveName', sa.String(length=64), nullable=True),
    sa.Column('electiveDescription', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initial_elective_list_electiveID'), 'initial_elective_list', ['electiveID'], unique=True)
    op.create_index(op.f('ix_initial_elective_list_electiveName'), 'initial_elective_list', ['electiveName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_initial_elective_list_electiveName'), table_name='initial_elective_list')
    op.drop_index(op.f('ix_initial_elective_list_electiveID'), table_name='initial_elective_list')
    op.drop_table('initial_elective_list')
    # ### end Alembic commands ###
